## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Печем в Суздале"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Приглашаю вас на творческие мастер-классы в Суздале: обережные куклы, крендели и ароматные пряники - традиции, которые оживают в ваших руках."
  images = ["./images/banner.webp"]
  favicon = true

[module]
  [[module.imports]]
    path = 'github.com/suzdal-tour/hugo-adapter-module'